### PR TITLE
Generalize pressure constants and make consistent with documentation

### PR DESCRIPTION
**Pull request by BrodiePearson**
This PR makes the pressure closure constants consistent with the Overleaf document. It also expands the pressure-tracer closure to include potential closure routes, and removes some now redundant parameters. Validation test and example of namelist are in the next post. 

## Summary of changes

- `C_2` and `(1-beta5)` $\rightarrow$ `C_b` (buoyancy pressure constant for momentum equations)
- `config_adc_c2` and `config_adc_beta5` $\rightarrow$ `config_adc_c_b` (associated namelist parameters)
.
.
- `alpha1 & alpha2` $\rightarrow$ `alpha_1 & alpha_2` (strain/vorticity-associated rapid pressure terms respectively)
- Hard-coded (no namelist parameters) $\rightarrow$ `config_adc_alpha_1 & config_adc_alpha_2`
.
.
- TKE-associated rapid pressure term $\rightarrow$ `alpha_0`
- Hard-coded as 0.8 $\rightarrow$ `config_adc_alpha_0`
.
.
- `gamma1` $\rightarrow$ `C_b_tracer` (buoyancy pressure constant for tracer equations)
- `config_adc_gamma1` $\rightarrow$ `config_adc_c_b_tracer`
.
.
- `cVel` $\rightarrow$ `C_slow` (slow pressure constant for momentum equations)
- `config_adc_cVel` $\rightarrow$ `config_adc_c_slow`
.
.
- `cvVel` $\rightarrow$ a new coefficient `slow_w_factor` **Used to be a separate slow coefficient for w2 budget. Now multiplies `C_slow` to adjust vertical velocity slow term constant, default is 0.875,  equivalent to previous defaults**
- `config_adc_cwVel` $\rightarrow$ `config_adc_slow_w_factor`
.
.
- `cSalt & cTemp` $\rightarrow$ Combined into one term`C_slow_tracer` (slow pressure constant for tracer equations)
- `config_adc_cTemp & config_adc_cSalt` $\rightarrow$ `config_adc_c_slow_tracer`
.
.
- `alpha3` $\rightarrow$ Split into `alpha_tracer1 & alpha_tracer2` (rapid pressure constants in tracer budgets)
- `config_adc_alpha3` $\rightarrow$ `(config_adc_alpha_tracer1 & config_adc_alpha_tracer2)`
- Previous single-parameter closure of [Canuto 2001](https://journals.ametsoc.org/view/journals/phoc/31/6/1520-0485_2001_031_1413_otpiop_2.0.co_2.xml), now generalized to a two-parameter closure [following Mironov 2001](https://rmets.onlinelibrary.wiley.com/doi/pdf/10.1002/qj.49712757106?casa_token=tYy156dAEgsAAAAA:jH6160d1kpnVHBKxDlBPzuyyvAn8m-UVZ6oQP2sj1o4OEp6TsJ1kIOTZZ_SHX6FzoMdUiD-BlIJKkyU). 

drawing

- Default values are set to produce Canuto version ($\alpha_3=0.8$) which requires $\alpha_{\phi 1} = \frac{3\alpha_3}{4} = 0.6$ and $\alpha_{\phi 2} = \frac{5\alpha_3}{4} = 1.0$.
- The freedom provided by the extra parameter allows production-cancellation style closures (for shear, $\alpha_{\phi 1}=\alpha_{\phi 2}$). I suspect this freedom will be critical for the Stokes closure, happy to lay out why in more detail.
.
.
- Also removed several parameters that are no longer used by ADC scheme, along with namelist pairs: `c_1, c1, c2, c8, c10`

### CODE REVIEW

**Comment by BrodiePearson** [comment]
A comparison of w2 for an old version of the code and a new version (with new paramaeters set to be identical to original parameters) produces identical w2 profiles. Adjusting the new constants causes significant deviations as expected (not shown).
drawing

## Namelist examples
### New ADC namelist

> &adcMixingModel
    config_adc_enable = .true.
    config_adc_timestep =  1
    config_adc_tau_o = 100
    config_adc_length_multiple = 2
    config_adc_epsilon = 0.0
    config_adc_use_old_length_scale = .true.
    config_adc_use_single_column = .true.
    config_adc_sigmat = 0.72
    config_adc_Ko = 4.574296
    config_adc_Cmom = 0.0
    config_adc_Ctherm = 0.0
    config_adc_Cmom_w3 = 5.0
    config_adc_c_b = 0.5
    config_adc_c_b_tracer = 0.33
    config_adc_alpha_0 = 0.8
    config_adc_alpha_1 = 0.984
    config_adc_alpha_2 = 0.568
    config_adc_alpha_tracer1 = 0.6
    config_adc_alpha_tracer2 = 1.0
    config_adc_c_slow = 2.0
    config_adc_c_slow_tracer = 2.0
    config_adc_slow_w_factor = 1.0
    config_adc_dissipation_constant = 1.0
    config_adc_CwwE = 1.
    config_adc_CwwD = 1.5
    config_adc_kappaFL = 0
    config_adc_kappaVAR = 0
    config_adc_kappaW3 = 0
/ 
 ### Equivalent old ADC namelist
> &adcMixingModel
    config_adc_enable = .true.
    config_adc_timestep =  1 
    config_adc_tau_o = 100
    config_adc_length_multiple = 2
    config_adc_epsilon = 0.0
    config_adc_use_old_length_scale = .true.
    config_adc_use_single_column = .true.
    config_adc_sigmat = 0.72
    config_adc_Ko = 4.574296
    config_adc_gamma1 = 0.33
    config_adc_beta5 = 0.5
    config_adc_c1 = 4.0
    config_adc_c2 = 0.5
    config_adc_Cmom = 0.0
    config_adc_Ctherm = 0.0
    config_adc_Cmom_w3 = 5.0 
    config_adc_cTemp = 2.0
    config_adc_cSalt = 2.0
    config_adc_cVel = 2.0
    config_adc_cwVel = 2.0
    config_adc_dissipation_constant = 1.0
    config_adc_CwwE = 1.
    config_adc_CwwD = 1.5
    config_adc_kappaFL = 0
    config_adc_kappaVAR = 0
    config_adc_kappaW3 = 0
/

**Comment by BrodiePearson** [comment]
Closes #15

**Comment by katsmith133** [comment]
Hi @BrodiePearson, I've tested these changes on my own branch. I get the same bit-for-bit match between the new and old parameters as you do for a slightly different case and I think these changes make sense with our documentation. I am good with this PR being merged.

**Review by katsmith133 — APPROVED** [review]

**Comment by vanroekel** [comment]
@BrodiePearson thanks for the PR. Could you or @katsmith133 confirm for me if this is truly BFB or just qualitatively identical?  If you take the diff with new and old do you get hard zero throughout?

**Comment by BrodiePearson** [comment]
@vanroekel I just checked and the w2 profiles I get with the old and new code are exactly identical. It's also worth noting that:
- The new namelists are working: changing any of the new parameters slightly changes the final w2 profile (except the alpha ones because I'm testing in a convective system with no uw, vw, shear, or stratification)
- The default values of all the new parameters are chosen to produce a system that is equivalent to the default version of the old parameters

**Comment by vanroekel** [comment]
great, thanks @BrodiePearson this is great.  Thanks for finishing this up.  This makes things much cleaner.

**Review by vanroekel — APPROVED** [review]
approving based on visual inspection and developer testing.

**Comment by vanroekel** [comment]
closes #15

**Pull request merged**
